---
version: '3'
services:
  consumer:
    image: golang:alpine
    volumes:
      - ./:/go/src/github.com/rafaeljesus/srv-consumer
    working_dir: /go/src/github.com/rafaeljesus/srv-consumer
    environment:
      AMQP_DSN: "amqp://guest:guest@rabbitmq:5672"
    command: go run cmd/main.go
    links:
          - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"

